name: Java CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GHIDRA_VERSION: 9.2.3
  GHIDRA_DATE: 20210325

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Ghidra
        run: |
          curl -O "https://ghidra-sre.org/ghidra_${GHIDRA_VERSION}_PUBLIC_${GHIDRA_DATE}.zip"
          unzip -q "ghidra_${GHIDRA_VERSION}_PUBLIC_${GHIDRA_DATE}.zip"
          echo "GHIDRA_INSTALL_DIR=$PWD/ghidra_${GHIDRA_VERSION}_PUBLIC" >> $GITHUB_ENV
        working-directory: ${{ env.TMPDIR }}

      - name: Build with Gradle
        run: ./gradlew

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libefidecompress.dylib
          path: os/osx64/libefidecompress.dylib

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Ghidra
        run: |
          Invoke-WebRequest "https://ghidra-sre.org/ghidra_${env:GHIDRA_VERSION}_PUBLIC_${env:GHIDRA_DATE}.zip" -OutFile "ghidra_${env:GHIDRA_VERSION}_PUBLIC_${env:GHIDRA_DATE}.zip"
          Expand-Archive "ghidra_${env:GHIDRA_VERSION}_PUBLIC_${env:GHIDRA_DATE}.zip" -DestinationPath .
          echo "GHIDRA_INSTALL_DIR=$pwd\ghidra_${env:GHIDRA_VERSION}_PUBLIC" >> ${env:GITHUB_ENV}
        working-directory: ${{ env.TEMP }}

      - name: Build with Gradle
        run: ./gradlew.bat

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: efidecompress.dll
          path: os/win64/efidecompress.dll

  build-linux:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Ghidra
        run: |
          curl -O "https://ghidra-sre.org/ghidra_${GHIDRA_VERSION}_PUBLIC_${GHIDRA_DATE}.zip"
          unzip -q "ghidra_${GHIDRA_VERSION}_PUBLIC_${GHIDRA_DATE}.zip"
          echo "GHIDRA_INSTALL_DIR=$PWD/ghidra_${GHIDRA_VERSION}_PUBLIC" >> $GITHUB_ENV
        working-directory: ${{ env.TMPDIR }}

      - name: Download macOS JNI library
        uses: actions/download-artifact@v2
        with:
          name: libefidecompress.dylib
          path: os/osx64

      - name: Download Windows JNI library
        uses: actions/download-artifact@v2
        with:
          name: efidecompress.dll
          path: os/win64

      - name: Build plugin with Gradle
        run: |
          ./gradlew
          echo "PLUGIN_DATE=$(find dist -name '*.zip' | awk -F '_' '{print $4}')" >> $GITHUB_ENV

      - if: github.ref == 'refs/heads/master'
        name: Upload to Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.zip
          tag: ${{ env.PLUGIN_DATE }}
          overwrite: true
          file_glob: true
